language: go
go:
  - 1.11.x
os:
  - linux
  - osx
  - windows
sudo: true
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
  - unset GOPATH
  - go test -v ./...
notifications:
  email:
    recipients:
      - i@sjis.me
    on_success: always
    on_failure: always