language: c
os:
  - linux
  - osx
  - windows
sudo: true
dist: trusty
install:
  - eval "$(curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | GIMME_GO_VERSION=master bash)"
script:
  - env GO111MODULE=on go build
  - env GO111MODULE=on go test
  - go test -v ./...
notifications:
  email:
    recipients:
      - i@sjis.me
    on_success: always
    on_failure: always