language: go
go:
  - 1.11.x
os:
  - linux
  - osx
  - windows
sudo: true
install:
  - go get -t ./...
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls
before_install:
  - go get -t -v ./...
script:
  - PATH="$HOME/gopath/bin:$PATH"
  - script/coverage --coveralls
notifications:
  email:
    recipients:
      - i@sjis.me
    on_success: always
    on_failure: always