language: go
go:
  - 1.11.x
os:
  - linux
  - osx
  - windows
sudo: true
before_install:
  - go get -t -v ./...
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
notifications:
  email:
    recipients:
      - i@sjis.me
    on_success: always
    on_failure: always